Fix bugs around the vacuuming of multixacts that can lead to corruption.
heap_freeze_tuple() didn't properly handle !LOCK_ONLY multixacts that
need to be frozen according to cutoff_multi where the updating xid was
above the xmin horizon. It simply unset xmax entirely - leading to
both, the old and the new version of a tuple, being visible.  Existing
corrupted rows unfortunately cannot be repaired in an automated
fashion.

Both heap_freeze_tuple() and heap_tuple_needs_freeze() forgot to look
into a multixact to check the members against cutoff_xid. That allowed
the clog to be truncated early, removing the entries for existing
multixact members, leading to errors when those rows then later were
accessed like following:
ERROR:  could not access status of transaction 3883960912
DETAIL:  Could not open file "pg_clog/0E78": No such file or directory.

This mostly was problematic when the updating transaction aborted,
since in that case the row wouldn't get pruned away earlier in vacuum
and the multixact could possibly survive for a long time.
In many cases data that is inaccessible that way can be brought back
heuristically.

Per bug report from F-Secure and J Smith.